<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.3">
  <POU Name="MAIN" Id="{8732fc72-5f01-4166-8591-38c357bf3993}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fbPower: MC_POWER;
	biLimFwd AT %I*: BOOL;
	biLimBwd AT %I*: BOOL;
	boBrake AT %Q*:BOOL;
	bEnable: BOOL := TRUE;
	bHalt AT %Q*: BOOL ;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
LadderLogic();

Axis1();
Axis2();
Axis3();
Axis4();
Axis5();
Axis6();

Axis7();
Axis8();
Axis9();
Axis10();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="73" Count="0" />
      <LineId Id="71" Count="0" />
      <LineId Id="41" Count="0" />
      <LineId Id="18" Count="0" />
      <LineId Id="40" Count="0" />
      <LineId Id="36" Count="0" />
      <LineId Id="32" Count="1" />
      <LineId Id="35" Count="0" />
      <LineId Id="60" Count="0" />
      <LineId Id="57" Count="2" />
      <LineId Id="19" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>