<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.3">
  <POU Name="GCC2" Id="{cd1af1d4-04a6-41fb-a0c2-978ed45d40cc}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM GCC2
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="GCC2">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>