<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.3">
  <POU Name="MAIN" Id="{955730b6-e55e-459f-b0b3-a88c3048e89d}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[GVL_ver.GCC2_xHV_DIS:=TRUE;
LadderLogic();
FB_KJL300();
FB_PBR260();
FB_TCP();
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="11" Count="0" />
      <LineId Id="2" Count="0" />
      <LineId Id="6" Count="1" />
      <LineId Id="15" Count="0" />
      <LineId Id="19" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>