<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.3">
  <POU Name="PTM1" Id="{a6d69970-ba4c-4978-992b-8d62b2a83208}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PTM1
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="PTM1">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>