<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.3">
  <POU Name="VCC2" Id="{4c9fc100-f02a-4673-9e05-021d5126852e}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM VCC2
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="VCC2">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>