<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.3">
  <POU Name="VCC3" Id="{814a955a-9b99-41f7-82d7-c96e3db38942}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM VCC3
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="VCC3">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>